pipeline {
    agent {
        docker { image 'eclipse-temurin:17-alpine' }
    }
    stages {
        stage('Create Java File') {
            steps {
                sh '''
                echo "public class Hello {" > Hello.java
                echo "    public static void main(String[] args) {" >> Hello.java
                echo "        System.out.println(\\"Hello from Jenkins Pipeline!\\");" >> Hello.java
                echo "    }" >> Hello.java
                echo "}" >> Hello.java
                '''
            }
        }
        stage('Compile') {
            steps {
                sh 'javac Hello.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java Hello'
            }
        }
    }
}
